src/taco-cli/cli/build.ts, src/taco-cli/cli/emulate.ts, src/taco-cli/cli/run.ts, src/taco-cli/test/build.ts, src/taco-cli/test/buildAndRunTelemetry.ts, src/taco-cli/test/emulate.ts, src/taco-cli/test/run.ts
With this change we try to build/run/emulate multiple platforms in parallel rather than sequentially.
This requires that we update some test expectations. Since we can build multiple remotes at once, we separate the remote servers to different ports to make the test expectations easier to check, and we update the test expectations so it no longer assumes that one build completes before the other starts, and thus some outputs of the first build could appear in the other.
=> Build parallel

src/taco-remote-lib/common/builder.ts, src/taco-remote-lib/ios/iosBuild.ts
This splits the iOS build function into a common core, and iOS specific components. We move some globals into class member variables, and gives a better base for moving to supporting other platforms. This also fixes some lingering tslint issues in iosBuild.ts
=> Refactoring iOS build function

tools/GulpUtils.ts
The gulp-tslint stream only emits an 'end' event, not a 'finished' event, so the streamToPromise function wasn't noticing the end and things ended in a deadlock.
=> Updating streamToPromise to handle 'end' events

src/remotebuild/lib/darwin/darwinCerts.ts, src/remotebuild/resources/en/resources.json
Now the UX looks like:
> ./remotebuild certificates reset
Warning: This command deletes all current client certificates. You will need to generate and configure a new security PIN. Do you want to continue? [Y]es or [N]o
y
Note: You need to restart any running remote build servers for this change to take effect, and have the certificates be actually reseted
>
=> Now we show a note after reseting the certificates, informing the user that he needs to reset the running servers for the change to take effect

src/taco-cli/cli/utils/cordovaWrapper.ts, src/taco-cli/cli/utils/kitHelper.ts, src/taco-utils/installLogLevel.ts, src/taco-utils/tacoPackageLoader.ts
Now we won't see all the npm warnings nor the output of all the package dependencies.
=> Now we hide the npm warnings and normal output while installing packages, but we still show errors

src/taco-cli/test/kit.ts, src/taco-cli/test/run.ts
Looks like some of the previous increased test timeouts didn't apply and I was just lucky that they didn't go over. I've moved their specification out of the before() handler and into the describe() handler.
Also increasing some other timeouts that failed, although that may have been a knock-on effect.
=> Bumping more test timeouts

src/taco-cli/test/create.ts
Changing the version from 5.2.0 to 4.3.0. This means that it matches the version used in other tests, and can be used from the cache rather than being redownloaded for this one test. Should improve test reliability.
=> Changing version of taco-cli used in test

src/taco-cli/test/build.ts, src/taco-cli/test/buildAndRunTelemetry.ts, src/taco-cli/test/create.ts, src/taco-cli/test/emulate.ts, src/taco-cli/test/help.ts, src/taco-cli/test/kit.ts, src/taco-cli/test/meta.ts, src/taco-cli/test/platformHelper.ts, src/taco-cli/test/platformPlugin.ts, src/taco-cli/test/remote.ts, src/taco-cli/test/run.ts, src/taco-cli/test/utils/commandHelper.ts
The motivation for this change is to construct command objects for tests in the same way that we do for production code. In particular, alias testing needs command objects constructed with the commands.json file for correct aliasing.
* Created static class CommandHelper which constructs the command object.
* Wherever we were new-ing command objects, a call to CommandHelper.getCommand is made.
* Clean up of no longer used imports.
=> Adding a static class to properly construct command objects for tests.

src/gulpmain.ts, tools/GulpUtils.ts
specify dependencies location but no actual files are dropped at
dropLocation
Moreover, fixing an issue where just-package fails because of previous
packaging artifacts
=> Changing the behavior so that dropLocation is just used as a variable to

src/taco-remote-lib/ios/ios.ts, src/taco-remote-lib/ios/iosEmulateHelper.ts, src/taco-remote-lib/package.json
ios-sim 5 uses a different approach to specify a simulation target, but we still support all the same previous inputs. As part of this change we also now allow the iOS version to be specified, but if the target/version combination doesn't exist on the server then it will fail.
=> Updating to ios-sim version 5

src/taco-utils/tacoPackageLoader.ts
Because variables were defined in the wrong order, the file regex was searching for "undefined" rather than "file://"
=> Fixing file:// handling in tacoPackageLoader

src/taco-utils/telemetryHelper.ts, src/typings/telemetryHelper.d.ts
Defines an object that can be passed to external modules (like `taco-simulate`) to report back telemetry events. It has a single method - `sendTelemetry()`.
Also, `sendCommandSuccessTelemetry()` and `sendCommandFailureTelemetry()` `args` parameter should be declared as optional, since it has a default value specified.
=> Adds support for creating an external telemetry object.

src/taco-cli/cli/remote.ts, src/taco-cli/cli/remoteBuild/remoteBuildClientHelper.ts
Some errors when attempting HTTP[S] communication will not have a "code" property, for example if a HTTPS connection is rejected because the server's hostname does not match the names on the certificate. This change make sure that we give appropriate errors rather than crashing.
=> Improving error handling with remotebuild

src/taco-cli/cli/remoteBuild/remoteBuildClientHelper.ts, src/taco-cli/cli/utils/projectHelper.ts, src/taco-cli/cli/utils/settings.ts, src/taco-remote-lib/common/builder.ts, src/taco-utils/tacoPackageLoader.ts
JSON.parse has the string type even though it accepts any object, so people will be forced to convert things to strings explicitly.
=> Changed calls to JSON.parse(fs.readFileSync()) to use 'utf8' so we don't need to cast the result of reading the file

src/taco-remote-lib/ios/iosBuild.ts, src/taco-remote-lib/package.json, src/taco-remote-lib/resources/en/resources.json
Cordova <5.3.3 breaks on node >=4.0.0 if the deployment-target or target-device preferences are specified in config.xml.
When run under remotebuild, this shows up as a deadlock which holds up all further processing. Now we check for
this combination and proactively reject the build with a message to the end user.
Addresses issue #96
=> Adding a check for incompatible node/cordova versions

src/taco-remote/package.json
Now that we've published 1.1.2 we need to bump this
=> Bumping taco-remote version number

src/taco-utils/telemetryHelper.ts
I meant to include this change with my earlier PR.
For consistency with other event name (like those generated by dependency installer), this combines the external event name using "/" instead of "." (so for `taco simulate`, for example, we end up with event names like `TACO/simulate/exec` instead of `TACO/simulate.exec`.
=> Combine external event name using "/" instead of "."

src/taco-cli/cli/utils/cordovaWrapper.ts
This method uses `cordova -v` to get the current Cordova version. That command returns the version in the following format:
5.3.3 (cordova-lib@5.3.3)
The existing logic wasn't stripping off the bit in brackets. As a result, calls to `semver` methods (such as `semver.gte()` in `CordovaWrapper.requirements()`) could throw an exception.
=> Fixes `CordovaWrapper.getGlobalCordovaVersion()` return value.

src/taco-cli/cli/create.ts, src/taco-cli/cli/kit.ts, src/taco-cli/cli/platform.ts, src/taco-cli/cli/plugin.ts, src/taco-cli/cli/utils/projectHelper.ts, src/taco-cli/resources/en/resources.json, src/taco-cli/test/kit.ts
1. Taco JSON should be updated only if user chose to update the project when presented with the choice
2. Fixing redundant status printing done when plugins are added/removed/updated
=> Project update (taco.json update) should happen only if user chooses "y" when presented with the choice

src/taco-remote-lib/ios/ios.ts, src/taco-remote-lib/ios/iosAppRunnerHelper.ts, src/taco-remote-lib/test/iosAppRunner.ts, src/taco-remote/lib/tacoRemoteConfig.ts
It seems that the time taken to communicate with the device can vary significantly between mac hosts, so I've bumped the default timeout and also allowed the end-user to specify the timeout if they desire.
=> Allowing user configuration of app launching timeout

src/remotebuild/package.json, src/remotebuild/test/help.ts, src/taco-cli/test/checkForNewerVersion.ts, src/taco-cli/test/create.ts, src/taco-cli/test/help.ts, src/taco-cli/test/platformPlugin.ts, src/taco-cli/test/remote.ts, src/taco-cli/test/templates.ts, src/taco-tests-utils/memoryStream.ts, src/taco-tests-utils/tacoTestsUtils.ts, src/taco-utils/helpCommandBase.ts, src/typings/memoryStream.d.ts, src/typings/tacoTestsUtils.d.ts
Added null guards to the HelpCommandBase when we resolve aliases. Added tests for remotebuild help, and some test refactoring.
* Added null checks to HelpCommandBase class when resolving aliases.
* Added tests for remotebuild help commands.
* Moved the MemoryStream class to the tacoTestUtils module.
* Added typings for MemoryStream.
* Updated existing tests that used MemoryStream
=> Fix remotebuild help crash and add tests

src/remotebuild/test/help.ts
Ensuring that the remotebuild help tests correctly configure and reset their preconditions. The nconf package is global-ish and can effect other tests. Also the process environment variable needs to be deleted and not set to a value.
* Moved nconf configuration to before()
* Added nconf reset to after()
* Deleting TACO_UNIT_TEST process environment variable.
=> Ensuring that test settings are isolated to the remotebuild help tests.

src/taco-dependency-installer/installers/androidPackagesInstaller.ts, src/taco-dependency-installer/test/androidPackagesInstaller.ts
- Moved skiped AndroidSdkInstaller tests to a new file androidPackagesInstaller.ts
- Fixed the tests
- Refactored some AndroidPackagesInstaller code
Manual tests:
* Run install-reqs with no Android SDK installed
* Run install-reqs when only the target is missing
* Run install-reqs when android.bat doesn't exit
* Run install-reqs when android.bat exits with an error code
* Run install-reqs when adb.exe doesn't exist (I removed it after it was installed)
=> Move old AndroidSdkInstaller tests that were related to the package installer, to the AndroidPackagesInstaller tests, and fixed them

src/taco-cli/test/help.ts, src/taco-cli/test/kit.ts, src/taco-remote/test/build.ts
Increasing the timeout on the taco-remote selftest, since we how include a plugin in the build which is acquired from the internet.
Also fixing a failure I introduced in the taco help tests, as well as improving the tests to show up failures as failures rather than timeouts.
=> Fixing CI tests

src/taco-cli/test/utils/mockCordova.ts, src/taco-remote-lib/common/builder.ts, src/taco-remote-lib/ios/iosBuild.ts, src/taco-remote-lib/package.json, src/taco-remote-lib/test/iosAppRunner.ts, src/taco-remote-multiplexer/dynamicDependencies.json, src/taco-remote-multiplexer/tacoRemoteMultiplexer.ts, src/taco-remote/test/build.ts, src/typings/cordovaExtensions.d.ts
Cordova 5.4.0 uses a new option type to pass arguments, and this change adapts to that. taco-remote-multiplexer now inspects the cordova version, and selects between a new version and the previous version depending on which cordova is targeted.
=> Updating taco-remote-lib to cope with cordova 5.4.0

src/taco-cli/cli/tacoErrorHelper.ts, src/taco-dependency-installer/tacoErrorHelper.ts, src/taco-kits/tacoErrorHelper.ts, src/taco-utils/tacoError.ts, src/taco-utils/tacoErrorHelper.ts, src/taco-utils/test/tacoErrors.ts, src/typings/tacoError.d.ts
There was a flaw in how TacoError extracted arguments meaning that errors often had incorrect information in them. This change fixes that error, corrects how variadic arguments are passed through, and adds in a test case to make sure that we catch future regressions.
=> Fixing some formatting issues with TacoError

src/taco-remote-lib/ios/ios.ts, src/taco-remote-lib/ios/iosAppRunnerHelper.ts, src/taco-remote-lib/ios/sharedState.ts
taco-remote-lib currently spawns two persistent processes for iOS related work: idevicedebugserverproxy and ios_webkit_debug_proxy. It keeps a hold of these processes in local variables, which starts to cause issues if we have multiple instances of the package around, such as now when we have different packages for cordova < 5.4.0 and >= 5.4.0
This change makes these processes into explicitly shared global state, allowing taco-remote-lib to share between packages.
This is one half of the change: identical changes are needed in taco-remote-lib@1.2.1
=> Fix concurrent taco remote lib packages

src/taco-cli/test/create.ts
We were explicitly requiring taco-kits in the create tests; I changed this to be lazily required
=> Remove kits from create tests

src/taco-remote-lib/ios/ios.ts
Currently trying to set up a debug pathway will throw an exception due to a missing require. This fix also needs to apply to taco-remote-lib 1.2.1
=> Adding missing require

src/taco-cli/cli/commands.json, src/taco-cli/cli/taco.ts, src/taco-cli/resources/en/resources.json, src/taco-dependency-installer/dependencyInstaller.ts, src/taco-dependency-installer/elevatedInstaller.ts, src/taco-dependency-installer/utils/installerUtils.ts, src/taco-dependency-installer/utils/win32/elevatedInstallerLauncher.ps1, src/taco-utils/tacoGlobalConfig.ts, src/taco-utils/utilHelper.ts, src/typings/tacoGlobalConfig.d.ts, src/typings/utilHelper.d.ts
Added a global ~~--accept~~ **Edit: changed to --no-prompt** parameter that gets saved in TacoGlobalConfig. This can be used by packages to react accordingly when prompting the user.
Also made DependencyInstaller honor that parameter.
=> --accept parameter

src/taco-remote/lib/buildRetention.ts
Currently the criteria for deleting a build excludes "installed" or "debugging" builds, which mean they clog up the pipeline. The more specific criteria below excludes only builds that are currently queued for building or actually building.
=> Changing definition of 'eligible for deletion' to only exclude builds in progress

src/remotebuild/lib/cli.ts, src/remotebuild/lib/server.ts, src/taco-cli/cli/taco.ts, src/taco-dependency-installer/elevatedInstaller.ts, src/taco-dependency-installer/test/androidPackagesInstaller.ts, src/taco-dependency-installer/test/androidSdkInstaller.ts, src/taco-dependency-installer/test/installerRunner.ts, src/taco-dependency-installer/test/javaJdkInstaller.ts, src/taco-remote/lib/buildManager.ts, src/taco-utils/telemetry.ts, src/typings/telemetry.d.ts
Adding basic telemetry points to remotebuild. Telemetry is captured on server start and per build.
* Added a new telemetry settings file for remotebuild.
* Added telemetry init/prompt to server start.
* Added telemetry after build complete.
=> Add Telemetry to Remotebuild

src/taco-utils/cordovaHelper.ts, src/taco-utils/cordovaWrapper.ts
`CordovaHelper.toCordovaArguments()` now returns cordova arguments in an appropriate format if Cordova >= 5.4.0 is used
=> Fix raw options warning

src/taco-cli/cli/remoteBuild/remoteBuildClientHelper.ts, src/taco-remote/lib/buildManager.ts
-Fixed TACO red error messages interleaving with remote build output on the client console
-Fixed build server reusing build log from previous builds
=> Fix remote build log issues

src/taco-remote-lib/package.json
ios-sim has an issue with launching the simulator for a different devicetypeid when the simulator is already running. We are working around this by setting our dependency to a known good version.
ios-sim issue:
https://github.com/phonegap/ios-sim/issues/187
=> Set ios-sim to a known good version

src/taco-remote-lib/common/builder.ts, src/taco-utils/cordovaHelper.ts
Changed Cordova raw options conversion for 5.4.0+ api: argv field now defaults to empty array instead of null
Fixes #256
=> Fix for issue #256

src/taco-remote-lib/common/builder.ts
The newer Cordova versions have stopped implicitly calling "prepare" when a platform is added. We must now always manually prepare platforms, whether we add the platform or not.
Fixes #259.
=> Fix for #259: Always prepare remote platforms

src/taco-remote-multiplexer/dynamicDependencies.json, src/taco-remote-multiplexer/package.json
I'm about to publish taco-remote-lib@1.3.0 and taco-remote-multiplexer@1.2.7, so this updates master with the newest version numbers.
=> Bumping versions after publishing taco-remote-lib@1.3.0

src/taco-cli/cli/kit.ts, src/taco-kits/test/validateMetadata.ts, src/taco-utils/npmHelper.ts, src/taco-utils/package.json, src/taco-utils/tacoPackageLoader.ts
With this change we to back to invoking npm on the command line rather than via its unstable internal APIs. Also fixing an issue where valid github URLs with a #branch specifier were misunderstood.
=> Updating TacoPackageLoader

src/taco-remote-lib/common/builder.ts, src/taco-remote-lib/ios/iosBuild.ts
To resolve issues with before/after build hooks not running, this commit removes some of the workarounds for outdated problems, and changes the implementation of res/native functionality to use the cordova-plugin-vs-taco-support.
=> Changing taco-remote-lib to use cordova-plugin-vs-taco-support

src/remotebuild/lib/server.ts
When uploading larger projects, some connections would be terminated unexpectedly.
I believe that it is related to https://blog.cloudflare.com/the-curious-case-of-slow-downloads/
and so I have increased the timout to work around that. If it is the linked issue, then a 5 minute timeout should be sufficient to allow arbitrary uploads.
Fixes #291
=> Increasing HTTP connection timeouts
