Microsoft/TACO

src/taco-cli/cli/plugin.ts
Updating the plugin command to handle both removing kit validated plugins
=> Handle Removing Kit Plugins

src/taco-dependency-installer/installers/androidSdkInstaller.ts
We no longer update the Tools package as part of Android SDK configuration step. The Tools package already comes installed by default with the Android SDK zip file.
This essentially is a workaround for the current Android SDK crash when updating from Tools 24.3.3 to Tools 24.4 on Windows. This also speeds up the install-reqs process, and helps being future-proof against breaking changes, because we now use a static version of the Tools package.
=> Fixed Android SDK install crash when updating the Tools package

src/taco-utils/test/cordovaConfig.ts
=> Fixing build break

src/taco-cli/test/checkForNewerVersion.ts
checkForNewerVersion was hiding some test failures as timeouts.
=> Improving checkForNewerVersion tests to handle errors correctly

src/taco-cli/cli/commands.json, src/taco-cli/cli/platform.ts, src/taco-cli/cli/plugin.ts, src/taco-cli/test/help.ts, src/taco-cli/test/platformPlugin.ts, src/taco-utils/commands.ts, src/taco-utils/helpCommandBase.ts, src/typings/commandAlias.d.ts, src/typings/commands.d.ts
Working on a better way to resolve command/subcommand aliases.
=> Better aliasing for commands

package.json, src/gulpmain.ts, src/taco-dependency-installer/installers/androidSdkInstaller.ts, src/taco-dependency-installer/installers/installerBase.ts, src/taco-dependency-installer/package.json, src/taco-dependency-installer/test/androidSdkInstaller.ts, src/taco-dependency-installer/test/installerRunner.ts, src/taco-tests-utils/.npmignore, src/taco-tests-utils/LICENSE, src/taco-tests-utils/nodeFakes.ts, src/taco-tests-utils/package.json, src/taco-tests-utils/tacoTestsUtils.ts, src/taco-tests-utils/telemetryFakes.ts, src/taco-tests-utils/telemetryTestsHelper.ts, src/taco-utils/package.json, src/taco-utils/processUtils.ts, src/taco-utils/promisesUtils.ts, src/taco-utils/tacoUtils.ts, src/taco-utils/telemetryHelper.ts, src/typings/mockery.d.ts, src/typings/node.d.ts, src/typings/nodeFakes.d.ts, src/typings/processUtils.d.ts, src/typings/promisesUtils.d.ts, src/typings/tacoTestsUtils.ts, src/typings/tacoUtils.d.ts, src/typings/telemetryFakes.d.ts, src/typings/telemetryHelper.d.ts
- Created a single test for install-reqs
- Created the infrastructure to make creating that test, and other similar tests easy
+ Used mockery to mock the required modules
+ Created a module with some node fakes to use as mocks with mockery
- Changed the existing installerRunner tests to actually verify that no telemetry is expected, and use the new fake telemetry generator
=> Created first test for install-reqs using mockery (also updated some old tests, and create some testing infrastructure)

src/gulpmain.ts, src/remotebuild/package.json, src/taco-cli/package.json, src/taco-dependency-installer/package.json, src/taco-kits/TacoKitMetadata.json, src/taco-kits/package.json, src/taco-remote-lib/package.json, src/taco-remote-multiplexer/dynamicDependencies.json, src/taco-remote-multiplexer/package.json, src/taco-remote-multiplexer/tacoRemoteMultiplexer.ts, src/taco-remote/package.json, src/taco-utils/package.json, src/taco-utils/tacoPackageLoader.ts, tools/GulpUtils.ts
following are the build/packaging improvements made into update branch (v1.0.2)
mostly now we can do "gulp build && gulp just-package" to generate dev/beta/release bits together
=> Sync v1.0.2

src/remotebuild/package.json, src/taco-cli/package.json, src/taco-dependency-installer/package.json, src/taco-kits/package.json, src/taco-remote-lib/ios/iosEmulateHelper.ts, src/taco-remote-lib/package.json, src/taco-remote-multiplexer/dynamicDependencies.json, src/taco-remote-multiplexer/package.json, src/taco-remote/package.json, src/taco-utils/package.json, tools/GulpUtils.ts
Also fixing a tslint issue and a bug in how dynamicDependencies.json was modified in dev
=> Bumping version numbers for next dev cycle

src/taco-kits/TacoKitMetadata.json
tacokit@2.0.0 will henceforth be our default kit
=> Default kit

src/taco-cli/cli/remoteBuild/remoteBuildClientHelper.ts
When remotebuild responds to a new build submssion, it includes a URL where more information can be found. When the client is connecting to the server via an ipv6 address this URL becomes malformed (e.g. the ipv6 address [abcd:1234::5678]:8080 is abbreviated to abcd:8080) and there is no good way to address that on the server. Instead we have the client ignore the host part of the URL and substitute the host that it wants to communicate with.
=> Fixing an issue with remotebuild and ipv6

src/taco-remote/lib/buildManager.ts
Addressing #106 on top of the previous release directly so we can get a fixed build out.
=> Hotfix: Fixing a bug in extracting plugins

src/gulpmain.ts, tools/GulpCoverageUtils.ts, tools/GulpUtils.ts
shorthands for other TACO gulp tasks
=> Adding --failTestsAtEnd (--ftae) for "taco run-tests". Also adding

src/gulpmain.ts, tools/GulpCoverageUtils.ts, tools/GulpUtils.ts
gulp run-tests with a custom reporter
=> Exposing mocha reporter to gulp. this is needed to make sure we can run

src/taco-remote/lib/selftest.ts
Also bumping cordova version in selftest for maximum nodejs compatibility
=> Refactoring selftest and adding check for plugins

CONTRIBUTING.md, README.md, tools/GulpUtils.ts, tools/gulpmain.ts
=> Adding notes around "how to contribute"

src/remotebuild/lib/cli.ts
Reported by Rido in our team, I thought I'd go ahead and just submit a pull request for this string change.
=> Updated copyright to include the current year

src/taco-cli/package.json, src/taco-cli/test/tacoErrors.ts, src/taco-dependency-installer/package.json, src/taco-dependency-installer/tacoErrorCodes.ts, src/taco-dependency-installer/test/tacoErrors.ts, src/taco-kits/package.json, src/taco-kits/test/tacoErrors.ts, src/taco-tests-utils/tacoErrorTestHelper.ts, src/taco-tests-utils/tacoTestsUtils.ts, src/taco-utils/package.json, src/taco-utils/test/tacoErrors.ts, src/typings/tacoErrorTestHelper.d.ts
test fix where wrong range is being used
@meenakb , @guillaumejenkins can you please take a look
=> Increasing the range for dependency installer error codes and fixing a

src/taco-tests-utils/package.json, src/taco-tests-utils/telemetryFakes.ts, src/taco-utils/package.json, src/taco-utils/tacoUtils.ts, src/taco-utils/test/tacoErrors.ts, src/typings/promisesUtils.d.ts, src/typings/telemetryHelper.d.ts
dependency.
Fix includes taco-tests-utils taking a proper dependency on taco-utils
and taco-utils removing it's dependency on taco-tests-utils
=> Fixing build break caused by commit bd6940e. Commit introduced a cyclic

src/taco-utils/tacoError.ts, src/taco-utils/telemetryHelper.ts, src/typings/tacoError.d.ts
Error name reference: https://msdn.microsoft.com/en-us/library/96s4ewf9(v=vs.94).aspx
=> Now we set the error code name as the name of the TacoError, and we send it in the telemetry

src/taco-cli/test/kit.ts, src/taco-utils/projectHelper.ts
Also added a test case to handle this case
=> parseUserJSON call got removed as part of refactoring. Adding it back.

src/taco-cli/test/help.ts
Fixed the help test failure introduced by changing the help for install-reqs
=> Fixed failing help test for install-reqs

src/taco-utils/package.json, src/taco-utils/telemetry.ts, src/typings/winreg.d.ts
Fixing three issues 
1. TACO hangs on VS dev comand prompts 
2. Response to telemetry prompt is printed twice on Mac
3. Machine ID never read from the registry on Mac
=> Telemetry fixes

tools/tacoUtil.js
Also modifying the success/failure messages
=> Fixing postinstall script to use exit codes instead of callbacks.

src/taco-kits/TacoKitMetadata.json, src/taco-kits/tacoKits.ts, src/taco-kits/test/tacoKits.ts, src/taco-kits/test/validateMetadata.ts, src/typings/tacoKits.d.ts
@meenakb , @joshuaskelton can you guys review this?
=> Adding a test case to validate current kit metadata

src/taco-cli/cli/commands.json, src/taco-cli/cli/emulate.ts, src/taco-cli/cli/run.ts, src/taco-cli/package.json, src/taco-cli/test/help.ts, src/taco-utils/cordovaWrapper.ts
- Commenting out references to livereload in run and emulate commands.
- Removed livereload and devicesync from command help.
- Removed livereload dependency.
=> Holding back livereload for the moment.

src/taco-cli/cli/commands.json, src/taco-cli/cli/emulate.ts, src/taco-cli/cli/run.ts, src/taco-cli/package.json, src/taco-cli/resources/en/resources.json, src/taco-cli/test/help.ts
- Unblocked livereload features
- Marked livereload features (beta)
=> Taco livereload

src/taco-utils/cordovaWrapper.ts
-Added missing return statement to promise chain
-Added typings to anonymous functions to avoid this issue in the future
=> Fix failing tests

templates/default/blank/config.xml, templates/default/typescript/config.xml
Added correct dimensions for the wp8 splash screen in config.xml for templates.
=> Changed config.xml file in templates

src/taco-livereload/lib/utils/ATSRemover.js
Correcting the globstar match.
Fixes #253
=> Only modify the correct plist file
